---
title: "Exercise 2"
author: "A Lubicka"
date: "14.04.2021"
output: html_document
params:
<<<<<<< HEAD
  season_num: 
    label: "Season number:"
    value: 1
    input: select
    choices: [1,2,3,4,5,6,7,8]
  plot_type: 
    label: "Choose plot type:"
    value: "lines"
    input: radio
    choiceNames: ["lines", "points"]  
    choiceValues: ["l","p"]
  printcode:
    label: "Display codes:"
    value: TRUE
=======
  season:
    label: "Season"
    value: 1
    input: slider
    min: 1
    max: 8
    step: 1
    sep: ""
>>>>>>> b919e06448873a9a05c1202e3d07c2042ca61794
---
```{r, include=F}
library(kableExtra)
library(tidyverse)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
<<<<<<< HEAD
load(paste0("../april_05_09/Data/season_", params$season_num, ".RData"))
```
# Game of Thrones - Season `r params$season_num` summary in numbers
=======
load(paste0("Data/season_", params$season,".RData"))
```

# Game of Thrones - Season `r params$season` summary in numbers
>>>>>>> b919e06448873a9a05c1202e3d07c2042ca61794

### __(*Warning:* spoilers ahead)__

***

### Overview

(From the [Wikipedia](https://en.wikipedia.org/wiki/Game_of_Thrones#Premise)) Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones.

Set on the fictional continents of Westeros and Essos, Game of Thrones has a large ensemble cast and follows several story arcs throughout the course of the show. A major arc concerns the Iron Throne of the Seven Kingdoms of Westeros through a web of political conflicts among the noble families either vying to claim the throne or fighting for independence from it. Another focuses on the last descendant of the realm's deposed ruling dynasty, who has been exiled to Essos and is plotting a return to the throne. A third story arc follows the Night's Watch, a military order defending the realm against threats from the North.

***

### Season `r params$season_num` summary

Season `r params$season_num` of Game of Thrones consisted of `r max(as.numeric(season_data$no_season))` episodes that aired between `r season_data$premiere_date[1]` and `r tail(season_data$premiere_date,1)`, `r substr(season_data$premiere_date,nchar(season_data$premiere_date)-10,nchar(season_data$premiere_date)-7)[1]` on HBO. The show gathered an average of `r round(mean(season_data$viewers),2)` first-day TV viewers in the US, with the number growing from `r season_data$viewers[1]` to `r tail(season_data$viewers,1)` million by the end of the season.

The most popular episode of the season was `r season_data[season_data$viewers == max(season_data$viewers),]$title`, in which:

> "`r season_data[season_data$viewers == max(season_data$viewers),]$description`"

***

You can see how the viewership of the episodes changed in Figure 1.

```{r viewers_plot}
plot(season_data$viewers, type= params$plot_type, col="red", lwd=5, xlab = "Episode number", ylab = "1st day TV viewers in the US (millions)")
```

***

Finally, the episodes with the above-average viewership were:

```{r}
library(dplyr)
season_data %>% select(no_season, title, directed_by) %>% filter(season_data$viewers > mean(season_data$viewers))
```
